### ISSUE TITLE
Perma-orange: browser_tabs.js AsyncShutdown Extension Shutdown timeout in profile-change-teardown

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2850]
```
 GECKO(1145) | FATAL ERROR: AsyncShutdown timeout in profile-change-teardown Conditions: [{"name":"Extension Shutdown: bug1273184@tests (null)","state":"(none)","filename":"resource://gre/modules/Extension.jsm","lineNumber":1170,"stack":["resource://gre/modules/Extension.jsm:shutdown:1170"]}] At least one completion condition failed to complete within a reasonable amount of time. Causing a crash to ensure that we do not leave the user with an [log…] 
 CRASH | devtools/client/aboutdebugging/test/browser_tabs.js | application crashed [@ mozalloc_abort] [log…] 
```

Linux: https://treeherder.mozilla.org/logviewer.html#?job_id=113154582&repo=pine&lineNumber=2362
Linux64: https://treeherder.mozilla.org/logviewer.html#?job_id=113157522&repo=pine&lineNumber=2237
OSX: https://treeherder.mozilla.org/logviewer.html#?job_id=113095121&repo=pine&lineNumber=3484

**Comment by tspurway** [comment]
Possibly a dev tools bug

**Comment by Mardak** [comment]
In tracking down a potential cause of reduced talos crashes, mconley noticed a patch https://github.com/mozilla/activity-stream/issues/2806#issuecomment-314883307

That same patch might be the source of this issue.

**Comment by Mardak** [comment]
This looks to be green all around now!
https://treeherder.mozilla.org/#/jobs?repo=pine&revision=bd89136b03d3391b9c15df8f598d67751ac56a21&filter-searchStr=dt9&selectedJob=113780920

**Comment by Mardak** [comment]
Bisected this to be fixed by `Bug 1364768 - Migrate away from IndexedDB for WebExtension startup cache`
https://bugzilla.mozilla.org/show_bug.cgi?id=1364768

This crash still existed with `Bug 1364768: Part 3 - Add helpers to serialize and deserialize compressed structured clone blobs. r=rhelmer` https://hg.mozilla.org/mozilla-central/rev/889cdd758898

Tests FAIL `browser_addons_remove.js | A promise chain failed to handle a rejection: aomStartup.encodeBlob is not a function - stack: null` with `Bug 1364768: Part 4 - Switch to a compressed, binary flat file for startup cache. r=aswan` https://hg.mozilla.org/mozilla-central/rev/46aae63fae91 and `Bug 1364768: Part 5 - Store the list of available locales in the startup cache. r=aswan` https://hg.mozilla.org/mozilla-central/rev/5637dcecb980

The last commit for the bug gets things working again and no crash with activity stream enabled: `Bug 1364768: Part 6 - Use startup cache for initial extension permission data. r=aswan` https://hg.mozilla.org/mozilla-central/rev/9dd2156225d3

**Comment by k88hudson** [comment]
Hurray!
